### ISSUE TITLE
Coverage for network is spotty on Ting. 

### ISSUE THREAD

**Issue by bobwonderful** [AOSP-JF-MM/issue_tracking_aosp#11]
I had predominately LTE coverage and don't think I went to 3G coverage on Ting (Sprint's network). There was no way to edit the APN's.  By the way this is before you guys started working on the separate branches for GSM vs CDMA.

**Comment by B--B** [comment]
Apn edits has been already fixed in our internal builds, we will release a CDMA build soon. And i saw that some Ting apn has been changed in latest days, hopefully lte will work without the need to edit the original apn

I keep this open until we release the public CDMA, in this way you can confirm if everything works fine

**Comment by B--B** [comment]
No report, i suppose it's fixed, i close this bug, please reopen if it's not fixed
