### ISSUE TITLE
Wifi connection unstable

### ISSUE THREAD

**Issue by SeppeColomba** [AOSP-JF-MM/issue_tracking_aosp#2]
So the wifi toggle stays on, but often the connection looses.
The toggle is still on, but it cant find any signals for like 10 seconds

**Comment by B--B** [comment]
It has been fixed in our latest release, no issue for me and all others testers for days, this can be closed

PS: https://code.google.com/p/android/issues/detail?id=78702 maybe related to this? It's a know aosp bug, not yet fixed reading the users reports, but happens only with eap ttls / eap peap mschapv2 / eap tls authentication
