### ISSUE TITLE
Charging Slowly

### ISSUE THREAD

**Issue by josephshenouda** [AOSP-JF-MM/issue_tracking_aosp#31]
Lockscreen says "charging slowly when plugged in. Takes for ever to charge. is this normal, and how do i fix this?

**Comment by FernBch** [comment]
This issue has been discussed many times in the AOSPA thread. It's a MM thing, not a ROM issue. The actual time to charge is unchanged from previous versions of Android. You see "Charging Slowly" because the Galaxy S4 does not support fast charge rates. This is a hardware limitation not a software one.
