### ISSUE TITLE
Network carrier search yields no results

### ISSUE THREAD

**Issue by civico** [AOSP-JF-MM/issue_tracking_aosp#32]
Currently, only automatic registration with cellular network works, as a search for network carriers yields not results.
While this affects only people staying close to another country's border, it is a big issue. In other words, big impact on reduced amount of users.

Model: **GT-I9505**
Baseband: **I9505XXUBMEA**
ROM: **20160110** 
Build: **MMB29T**

**Comment by B--B** [comment]
Already fixed by me and Alucard, see here: https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/commit/68edae64940275f086a8e1310388265827cc6462 and here: https://github.com/AOSP-JF-MM/platform_device_samsung_jflte/commit/68a8e45e54f567db9101c2354a66a71e9412f121 

Will be available soon when we' ll release the next beta :-)
