### ISSUE TITLE
Gallery Crashes while in guest mode

### ISSUE THREAD

**Issue by 007craft** [AOSP-JF-MM/issue_tracking_aosp#55]
If you go into guest mode Gallery will stop working within 30 seconds.  Especially if you open gallery then back out and open another app.  Once it crashes, it works again but now it shows all the pictures and videos on the phone, somewhat defeating the purpose of guest mode.  It wont crash again after this.

This is on a Galaxy S4 sgh-i337m

**Comment by B--B** [comment]
This issue belongs to MM, but next release will be the last, so i close this as MM reached the EOL, N is our stable release now, and unfortunately i have no time to keep two different ROMs alive for multiple devices, BTW with N stable and bug free (wifi hotspot will be fixed in next upcoming release) i don't see the sense to stay with an older android release and OMS working only in legacy mode
