### ISSUE TITLE
Lag when scrollung up/down

### ISSUE THREAD

**Issue by FernBch** [AOSP-JF-MM/issue_tracking_aosp#76]
Device: SCH-I545 OF1 modem
Clean Flash of AOSP-6.0-20160615-jflte.zip
Np system mods.

When scrolling up/down in any open app theere are lags, stutters, etc on the display. Spmetimes lasts as long as 2-3 seconds.

Logcat:

https://www.dropbox.com/s/ixtd6sf50u2q3x3/Log_2016-06-18_20-36-12.txt?dl=0

**Comment by B--B** [comment]
Try the latest release (18), it's working fine for me

**Comment by FernBch** [comment]
Still present but isn't as pronounced.

https://www.dropbox.com/s/3550omllioaffar/Log_2016-06-19_19-25-39.txt?dl=0

I may make some changes in STweaks and see if it makes an improvement.

**Comment by FernBch** [comment]
I flaahed 21/06 today. Only been up and running for about an hour. Looks good so far. I'll report back in the next 24 hours.

**Comment by FernBch** [comment]
The issue has improved but s still present.

https://www.dropbox.com/s/k19hip3kjfyhpk4/Log_2016-06-24_09-33-55.txt?dl=0

**Comment by FernBch** [comment]
Flashed July 3 build. Issue persists.

New Logcat

https://www.dropbox.com/s/nebg9jrt48d7vd3/Log_2016-07-05_17-15-08.txt?dl=0

**Comment by FernBch** [comment]
Still present in 09/07 release

**Comment by B--B** [comment]
No one reported this issue in 09/07 public release, so probably it's something related to your device

WindowManager: Screen frozen for +550ms due to Window{828bc3e u0 com.teslacoilsw.launcher/com.teslacoilsw.launcher.NovaLauncher}

Your log is full of this, it's NovaLauncher your problem, but i know that @smeroni68 use Nova too and does not have this issue..

**Comment by FernBch** [comment]
Ok. I guess I'll go to Tespacoil for bug reporting on this.

Thanks
