### ISSUE TITLE
Use "stock" rounded corners in recents view

### ISSUE THREAD

**Issue by navhaxs** [AOSP-JF-MM/issue_tracking_aosp#77]
I made a really simple pull request at https://github.com/AOSP-JF-MM/platform_frameworks_base/pull/1
which uses the rounded corner value from upstream. Not sure if that was the right place - would you consider merging?

Just for the cosmetic look only. I recently discovered that I can make my own layers theme just to customise that value for my own use - and also that the layers engine supports multiple overlays at the same time, so other themes can still be used.

**Comment by B--B** [comment]
This issue belongs to MM, but next release will be the last, so i close this as MM reached the EOL, N is our stable release now, and unfortunately i have no time to keep two different ROMs alive for multiple devices, BTW with N stable and bug free (wifi hotspot will be fixed in next upcoming release) i don't see the sense to stay with an older android release and OMS working only in legacy mode
