### ISSUE TITLE
UI issue, low priority, Charging icon

### ISSUE THREAD

**Issue by codeseven58** [AOSP-JF-MM/issue_tracking_aosp#92]
I have the charging icon, in the notification bar, set to circle with charge number inside the circle. The circle used to rotate while it is charging but no longer does that. However when I frag down the notification bar, the icon then acts normally and rotates.

**Comment by dkati** [comment]
mi5 or jf mister :) ?

**Comment by B--B** [comment]
This issue belongs to MM, but next release will be the last, so i close this as MM reached the EOL, N is our stable release now, and unfortunately i have no time to keep two different ROMs alive for multiple devices, BTW with N stable and bug free (wifi hotspot will be fixed in next upcoming release) i don't see the sense to stay with an older android release and OMS working only in legacy mode
